# MCU name
MCU = RP2040
BOOTLOADER = rp2040

AUTO_SHIFT_ENABLE = yes
COMBO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes
QMK_SETTINGS = yes
BOOTMAGIC_ENABLE = yes


SERIAL_DRIVER = vendor
WS2812_DRIVER = vendor
