# MCU name
MCU = RP2040
BOOTLOADER = rp2040

DYNAMIC_MACRO_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes
QMK_SETTINGS = yes
BOOTMAGIC_ENABLE = yes
AUTO_SHIFT_ENABLE = no
COMBO_ENABLE = no


SERIAL_DRIVER = vendor
WS2812_DRIVER = vendor
